#ifndef _MACRO_DEF_H
#define _MACRO_DEF_H

#define CBRS_ARRANGE_TOPLEFT    1
#define CBRS_ARRANGE_TOPRIGHT   2
#define CBRS_ARRANGE_BOTTOMLEFT 4
#define CBRS_ARRANGE_BOTTOMRIGHT 8

#define CBRS_ARRANGE_LEFT       ( CBRS_ARRANGE_TOPLEFT  | CBRS_ARRANGE_BOTTOMLEFT )
#define CBRS_ARRANGE_TOP    ( CBRS_ARRANGE_TOPRIGHT | CBRS_ARRANGE_TOPLEFT )

#define WM_ADDCONTEXTMENUITEMS  (WM_USER + 1)   // Add to context menu message
#define WM_USER_AFTERFLOAT_MSG  (WM_USER + 2)

#endif