//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// OOD.rc에서 사용되고 있습니다.
//
#define IDYESALWAYS                     8
#define IDNOALWAYS                      9
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_POSITION           101
#define IDR_MAINFRAME                   120
#define IDR_USECASEFRAME                121
#define IDR_SEQUENCEFRAME               122
#define IDR_COLLABORATIONFRAME          123
#define IDR_STATEFRAME                  124
#define IDR_ACTIVITYFRAME               125
#define IDR_DEPLOYMENTFRAME             126
#define IDR_OBJECTFRAME                 127
#define IDR_CLASSFRAME                  128
#define IDR_TEXTFRAME                   129
#define IDR_COMMONFRAME                 130
#define IDD_NEWDLG                      138
#define IDR_TREEBAR_IMAGE               139
#define IDR_TB_CLASS                    142
#define IDR_TB_USECASE                  145
#define IDR_TB_SEQUENCE                 147
#define IDR_TB_COLLABORATION            151
#define IDR_TB_STATE                    153
#define IDR_TB_ACTIVITY                 155
#define IDR_TB_DEPLOYMENT               157
#define IDR_WS_CLASSVIEW_BITMAP         172
#define IDR_WS_DIAGRAMVIEW_BITMAP       173
#define IDD_NEWWSDLG                    174
#define IDD_CHOOSE_DIR                  176
#define IDR_DIRECTORY_BITMAP            177
#define IDR_WS_FILEVIEW_BITMAP          179
#define IDR_WS_INFOVIEW_BITMAP          180
#define IDD_PROJECT_OPTIONS_DLG         181
#define IDD_PROJECT_OPTIONS_GENERAL     184
#define IDD_PROJECT_OPTIONS_CODEGEN     186
#define IDD_PROJECT_OPTIONS_REVERSE     188
#define IDD_CPP_METHOD_PROP_DLG         190
#define IDD_MEMBER_PROP_DLG             191
#define IDD_VCPP_METHOD_PROP_DLG        192
#define IDD_CPP_METHOD_PROP_GENERAL     193
#define IDD_COMMENT_DLG                 194
#define IDD_METHOD_BODY_DLG             195
#define IDD_VCPP_METHOD_PROP_GENERAL    196
#define IDD_JAVA_METHOD_PROP_DLG        198
#define IDD_JAVA_METHOD_PROP_GENERAL    199
#define IDD_CPP_VAR_PROP_DLG            201
#define IDD_JAVA_VAR_PROP_DLG           202
#define IDD_VCPP_VAR_PROP_DLG           203
#define IDD_CPP_VAR_PROP_GENERAL        204
#define IDD_VCPP_VAR_PROP_GENERAL       205
#define IDD_JAVA_VAR_PROP_GENERAL       206
#define IDD_CLASS_PROP_DLG              217
#define IDD_CPP_CLASS_PROP_GENERAL      220
#define IDD_DATA_MEMBERS                222
#define IDD_MEMBER_FUNCTIONS            223
#define IDD_JAVA_CLASS_PROP_GENERAL     224
#define IDD_VCPP_CLASS_PROP_GENERAL     226
#define IDD_VCPP_CLASS_PROP_MAPS        228
#define IDD_VCPP_MAP_EDITOR             229
#define IDR_TB_CUSTOM                   231
#define IDD_PROJECT_OPTIONS_MACROS      232
#define IDD_CLASS_DOCUMENT_DLG          233
#define IDD_BASE_CLASS_INIT_DLG         234
#define ID_COMBO_ZOOM                   235
#define IDD_WIDE_STATE_DLG              236
#define ID_OLE_ADAPT_VIEW_FRAME         237
#define IDD_TIP_DIALOG                  238
#define IDB_TIP                         239
#define IDD_SCREEN_CAPTURE_DLG          240
#define IDD_CAPTURE_DLG                 241
#define IDR_BROWSER_POPUPS              242
#define IDD_QUERY_TEXT_DIALOG           243
#define IDD_RELATION_TRAVERSE_DLG       244
#define IDR_DUMMY_FRAME                 246
#define IDD_PACKAGE_PROP_DLG            247
#define IDD_PACKAGE_COMMENT_DLG         248
#define IDD_PACKAGE_PROP_GENERAL        249
#define IDR_OOD_CNTR_IP                 250
#define IDD_OBJECT_POSITION_DLG         251
#define IDR_OLE_POPUPS                  252
#define IDR_OOD_SRVR_IP                 254
#define IDR_OOD_SRVR_EMB                255
#define IDD_CSHARP_CLASS_PROP_GENERAL   260
#define IDD_CSHARP_METHOD_PROP_GENERAL  262
#define IDD_CSHARP_VAR_PROP_GENERAL     264
#define IDD_WHICHDLG                    271
#define IDD_CLASS_MIGRATION_DLG         273
#define IDD_CLASS_DEL_DLG               274
#define IDD_CLASS_OTHERS                276
#define IDC_EDIT_NAME                   1000
#define IDC_NAME                        1001
#define IDC_EDIT_LOCATION               1002
#define IDC_FILE_TYPE_LIST              1003
#define IDC_DIR_BUTTON                  1004
#define IDC_COMBO_LANGUAGE              1005
#define IDC_EDIT_DIR_NAME               1006
#define IDC_COMBO_SF_EXTENSION          1007
#define IDC_COMBO_DRIVE_NAME            1009
#define IDC_TREE_DIRS                   1011
#define IDC_TAB_PROJECT_OPTIONS         1012
#define IDC_EDIT_AUTHOR                 1036
#define IDC_EDIT_ORGANIZATION           1037
#define IDC_COMBO_HF_EXTENSION          1038
#define IDC_EDIT_TARGET_DIR             1039
#define IDC_BUTTON_CHOOSE_DIR           1040
#define IDC_EDIT_SOURCE_DIR             1041
#define IDC_RADIO_YES                   1042
#define IDC_RADIO_NO                    1043
#define IDC_COMBO_TREE_ORIENT           1044
#define IDC_TAB_CPP_METHOD_PROP         1045
#define IDC_TAB_MEMBER_PROP             1046
#define IDC_TAB_VCPP_METHOD_PROP        1047
#define IDC_COMBO_VISIBILITY            1051
#define IDC_EDIT_EXCEPTION              1052
#define IDC_EDIT_COMMENT                1058
#define IDC_EDIT_METHOD_BODY            1059
#define IDC_CHECK_INLINE                1062
#define IDC_CHECK_CONST                 1063
#define IDC_TAB_JAVA_METHOD_PROP        1064
#define IDC_CHECK_ABSTRACT              1065
#define IDC_STATIC_SIGNATURE            1068
#define IDC_STATIC_MEMBER_NAME          1069
#define IDC_BUTTON_NEXT                 1070
#define IDC_BUTTON_PREV                 1072
#define IDC_CHECK_STATIC                1073
#define IDC_COMBO_TYPE                  1074
#define IDC_EDIT_DEFAULT_VALUE          1075
#define IDC_CHECK_TRANSIENT             1078
#define IDC_CHECK_SYNCHRONIZED          1080
#define IDC_CHECK_NATIVE                1081
#define IDC_CHECK_VIRTUAL               1092
#define IDC_STATIC_EQUAL                1093
#define IDC_CHECK_AFXMSG                1095
#define IDC_CHECK_AFXDATA               1096
#define IDC_CHECK_MFCVIRTUAL            1097
#define IDC_CHECK_FINAL                 1098
#define IDC_EDIT_MEMBER_NAME            1100
#define IDC_STATIC_CLASS_NAME           1101
#define IDC_LIST_WISH                   1104
#define IDC_TAB_CLASS_PROP              1105
#define IDC_COMBO_STEREOTYPE            1108
#define IDC_CHECK_CONCRETE              1109
#define IDC_EDIT_DATA_MEMBER            1111
#define IDC_BUTTON_NEW                  1112
#define IDC_BUTTON_UPDATE               1113
#define IDC_BUTTON_DELETE               1114
#define IDC_STATIC_FOR_NAME             1117
#define IDC_LIST_DATA_MEMBERS           1120
#define IDC_LIST_MEMBER_FUNCTIONS       1121
#define IDC_EDIT_MEMBER_FUNCTION        1122
#define IDC_CHECK_MFC_CLASS             1123
#define IDC_CHECK_SERIALIZABLE          1124
#define IDC_CHECK_DYNAMIC               1125
#define IDC_CHECK_DYNCREATE             1126
#define IDC_BUTTON_ADD                  1127
#define IDC_BUTTON_EDIT                 1128
#define IDC_LIST_SYSTEM_MAPS            1129
#define IDC_LIST_CLASS_MAPS             1130
#define IDC_EDIT                        1131
#define IDC_STATIC_BEGIN                1132
#define IDC_STATIC_END                  1133
#define IDC_CHECK_AFXFIELD              1134
#define IDC_EDIT_HEADERFILE             1135
#define IDC_EDIT_SOURCEFILE             1136
#define IDC_RADIO_HF_FRONT              1137
#define IDC_RADIO_SF_FRONT              1138
#define IDC_RADIO_HF_MIDDLE             1139
#define IDC_RADIO_HF_END                1140
#define IDC_EDIT_DOCUMENT               1141
#define IDC_BUTTON_SAVE                 1142
#define IDC_BUTTON_RESET                1143
#define IDC_EDIT_RESOURCE_ID            1144
#define IDC_BUTTON_MORE                 1145
#define IDC_EDIT_INIT_VALUE             1146
#define IDC_EDIT_INNER_CLASS_OF         1147
#define IDC_EDIT_NUMBER                 1147
#define IDC_COMBO_NUMBER                1148
#define IDC_CHECK_START_UP              1150
#define IDC_RADIO_VIEW                  1151
#define IDC_RADIO_USER_RECT             1152
#define IDC_EDIT_BMP_FILE_NAME          1153
#define IDC_EDIT_ANSWER                 1156
#define IDC_STATIC_QUESTION             1157
#define IDC_BUTTON_PROPERTIES           1158
#define IDC_COMBO_RELATIONSHIP          1159
#define IDC_COMBO_ORIENT                1160
#define IDC_STATIC_PACKAGE_NAME         1161
#define IDC_TAB_PACKAGE_PROP            1162
#define IDC_EDIT_X                      1163
#define IDC_EDIT_Y                      1164
#define IDC_EDIT_WIDTH                  1165
#define IDC_CHECK_INTERNAL              1165
#define IDC_EDIT_HEIGHT                 1166
#define IDC_CHECK_EXTERN                1166
#define IDC_CHECK_OVERRIDE              1167
#define IDC_CHECK_READONLY              1168
#define IDC_COMBO_DESTINATION           1169
#define IDC_STATIC_CLOSING_BRACE        1171
#define IDC_EDIT_DIRECTORY              1172
#define IDC_EDIT_FILE_NAME              1173
#define IDC_CHECK_CODE                  1174
#define ID_VIEW_WORKSPACE               32771
#define ID_TEST                         32775
#define ID_FONT                         32776
#define ID_TOOLS_FONT                   32777
#define ID_TB_CLASSTEMPLATE             32779
#define ID_TB_TEMPLATECLASS             32780
#define ID_TB_INTERFACE                 32781
#define ID_TB_UTILITY                   32782
#define ID_TB_PACKAGE                   32783
#define ID_TB_GENERALIZATION            32784
#define ID_TB_REFINEMENT                32785
#define ID_TB_AGGREGATION               32786
#define ID_TB_COMPOSITION               32787
#define ID_TB_DEPENDENCY                32788
#define ID_TB_ASSOCIATION               32789
#define ID_TB_ACTOR                     32790
#define ID_TB_USECASE                   32791
#define ID_TB_USECASE_SYSTEM            32792
#define ID_TB_USECASE_ASSOCIATES        32793
#define ID_TB_USECASE_USES              32794
#define ID_TB_USECASE_EXTENDS           32795
#define ID_TB_SEQUENCE_OBJECT           32796
#define ID_TB_SEQUENCE_SYNC             32797
#define ID_TB_SEQUENCE_ASYNC            32798
#define ID_TB_SEQUENCE_RETURN           32799
#define ID_TB_COL_OBJECT                32800
#define ID_TB_COL_MULTI_OBJECT          32801
#define ID_TB_COL_MESSAGE               32802
#define ID_TB_STATE                     32803
#define ID_TB_INITIAL_STATE             32804
#define ID_TB_FINAL_STATE               32805
#define ID_TB_TRANSITION                32806
#define ID_TB_ACTIVITY                  32807
#define ID_TB_SYNC_BAR                  32810
#define ID_TB_BEGIN_ACTIVITY            32811
#define ID_TB_END_ACTIVITY              32812
#define ID_TB_TRIGGER                   32813
#define ID_TB_HWNODE                    32814
#define ID_TB_DEP_COMPONENT             32815
#define ID_TB_HW_CONNECTION             32816
#define ID_TB_DEP_COMMUNICATION         32817
#define ID_TB_DEP_HW_CONNECTION         32818
#define ID_TB_DEP_DEPENDENCY            32820
#define ID_VIEW_MODEL_TOOLBAR           32821
#define ID_WINDOW_CLOSE                 32822
#define ID_WINDOW_CLOSE_ALL             32823
#define ID_WINDOW_NEXT                  32824
#define ID_WINDOW_PREVIOUS              32825
#define ID_TB_ARROW                     32826
#define ID_TB_ALPHABET                  32827
#define ID_TB_NOTE                      32828
#define ID_FILE_OPEN_WORKSPACE          32845
#define ID_FILE_NEW_WORKSPACE           32847
#define ID_FILE_SAVE_WORKSPACE          32848
#define ID_FILE_CLOSE_WORKSPACE         32849
#define ID_OPTIONS_PROJECT              32851
#define ID_CLASS_TOOLS_OPTIONS          32854
#define ID_FILE_MRU_WORKSPACE           32855
#define ID_VIEW_ZOOMBAR                 32857
#define ID_SCREENSHOT                   32860
#define ID_VIEW_CUSTOMBAR               32861
#define ID_TB_ANCHOR                    32862
#define ID_TB_WIDE_STATE                32863
#define ID_TB_WIDE_PACKAGE              32864
#define ID_TIP_OF_THE_DAY               32866
#define ID_CLASS_ROOT_NEW_PACKAGE       32868
#define ID_PACKAGE_NEW_CLASS            32869
#define ID_CLASS_GO_TO_DEFINITION       32870
#define ID_CLASS_ADD_MEMBER_FUNCTION    32871
#define ID_CLASS_ADD_MEMBER_VARIABLE    32872
#define ID_PACKAGE_PROPERTIES           32875
#define ID_FUNCTION_PROPERTIES          32876
#define ID_DATA_PROPERTIES              32877
#define ID_PACKAGE_OPEN                 32878
#define ID_CLASS_RELATED_CLASSES        32879
#define ID_DELETE_RELATIONSHIP          32880
#define ID_DIAGRAM_TYPE_NEW_DIAGRAM     32881
#define ID_DIAGRAM_OPEN                 32882
#define ID_DIAGRAM_DELETE               32883
#define ID_FILE_TYPE_NEW_FILE           32884
#define ID_FILE_MENU_OPEN               32885
#define ID_FILE_MENU_DELETE             32886
#define ID_INSERT_OBJECT                32887
#define ID_OBJECT_EDIT                  32889
#define ID_OBJECT_OPEN                  32890
#define ID_OBJECT_TRANSPARENT           32892
#define ID_OBJECT_PROPERTIES            32893
#define ID_EDIT_DELETE                  32894
#define ID_CANCEL_EDIT_CNTR             32895
#define ID_CANCEL_EDIT_SRVR             32896
#define ID_FILE_SAVE_AS_WORKSPACE       32901
#define ID_FILE_SAVE_AS_PACKAGE         32902
#define ID_BAR_HIDE                     32903
#define ID_BAR_MDIFLOAT                 32904
#define ID_BAR_CUSTOMIZE                32905
#define IDS_BAR_STARTDOCKING            32906
#define ID_BAR_ALLOWDOCKING             32907
#define ID_VIEW_DOCUMENTATION           32908
#define ID_CREATE_CLASSTEMPLATE         32909
#define ID_CREATE_STATE                 32910
#define ID_CREATE_GENERALIZATION        32911
#define ID_CREATE_AGGREGATION           32912
#define ID_CREATE_DEPENDENCY            32913
#define ID_POPUP_EDIT                   32914
#define ID_CREATE_PACKAGETEMPLATE       32915
#define ID_CREATE_COMPOSITION           32916
#define ID_CREATE_INITIAL_STATE         32917
#define ID_CREATE_FINAL_STATE           32918
#define ID_CREATE_TRANSITION            32919
#define ID_CREATE_BEGIN_ACTIVITY        32920
#define ID_CREATE_END_ACTIVITY          32921
#define ID_CREATE_SYNCHRONIZATION_BAR   32922
#define ID_CREATE_ACTIVITY              32923
#define ID_CREATE_TRIGGER               32924
#define ID_CREATE_ACTOR                 32925
#define ID_CREATE_USECASE               32926
#define ID_CREATE_COLLABORATION_OBJECT  32927
#define ID_CREATE_MESSAGE_FLOW          32928
#define ID_CREATE_USECASELINK           32929
#define ID_CREATE_USECASEUSESLINK       32930
#define ID_CREATE_USECASEEXTENDSLINK    32931
#define ID_CREATE_SYSTEMBOUNDARY        32932
#define ID_MESSAGE_MESSAGE_FLOW         32933
#define ID_SHIFT_ARROW_MESSAGE_TEXT     32934
#define ID_INVERT_ARROW_MESSAGE_TEXT    32935
#define ID_CREATE_COLLABORATION_MULTI_OBJECT 32936
#define ID_SELF_DELEGATION_COLLABORATION_OBJECT 32937
#define ID_CREATE_HARDWARE_NODE         32938
#define ID_CREATE_COMPONENT_TEMPLATE    32939
#define ID_CREATE_HWCONNECTION          32940
#define ID_CONNECTION_NAME_EDIT         32941
#define ID_CREATE_COMMUNICATION         32942
#define ID_CREATE_ASSOCIATION           32943
#define ID_CREATE_SEQUENCE_OBJECT       32944
#define ID_ACTIVATION_SEQUENCE_OBJECT   32945
#define ID_CREATE_SYNC_MESSAGE          32946
#define ID_DELETE_FIGURE                32947
#define ID_CREATE_ASYNC_MESSAGE         32948
#define ID_CREATE_RETURN_MESSAGE        32949
#define ID_ACTIVATION_KILL_SIGN         32950
#define ID_SEQUENCE_SELF_DELEGATION     32951
#define ID_CLASSTEMPLATE_SIZE           32952
#define ID_CREATE_INTERFACE             32953
#define ID_CREATE_UTILITY               32954
#define ID_CRETAE_TEMPLATECLASS         32955
#define ID_SUPRESS_DATA_MEMBERS         32956
#define ID_SUPRESS_MEMBER_FUNCTIONS     32957
#define ID_EDIT_ROLE_NAME               32958
#define ID_EDIT_MULTIPLICITY            32959
#define ID_EDIT_QUALIFICATION           32960
#define ID_CREATE_REFINEMENT            32961
#define ID_CREATE_ASSOCIATION_CLASS     32962
#define ID_CREATE_INTERFACE_PORT        32963
#define IDC_TREEBAR_TAB                 32964
#define ID_POPUP_OPEN_PACKAGE           32965
#define ID_GENERATE_CODE                32966
#define IDC_FILETREECTRL                32967
#define IDC_DIAGRAMTREECTRL             32968
#define IDC_INFOTREECTRL                32969
#define IDR_ZOOM_TOOL_BAR               32970
#define ID_CLASS_PROPERTIES             32971
#define ID_INTERFACE_PROPERTIES         32972
#define ID_CREATE_WIDE_STATE            32973
#define ID_CREATE_WIDEPACKAGE           32974
#define ID_TIP_BOARD                    32975
#define IDP_OLE_INIT_FAILED             32976
#define IDP_FAILED_TO_CREATE            32977
#define ID_POPUP_EDIT_PASTE             32980
#define ID_SELF_DELEGATION_DELETE       32981
#define ID_PACKAGE_DELETE               32985
#define ID_CLASS_DELETE                 32986
#define ID_MEMBER_DELETE                32987
#define ID_CLASS_MIGRATE                32988
#define ID_TOOLS_GRID                   32989
#define ID_TOOLS_COLOR_PAPER            32990
#define ID_TOOLS_COLOR_TEXT             32992
#define ID_TOOLS_COLOR_SHAPE_FOREGROUND 32994
#define ID_TOOLS_COLOR_SHAPE_BACKGROUND 32995
#define ID_VIEW_REFRESH                 32997
#define ID_VIEW_ZOOM_100                32998
#define ID_VIEW_ZOOM_90                 33000
#define ID_VIEW_ZOOM_80                 33001
#define ID_VIEW_ZOOM_70                 33002
#define ID_VIEW_ZOOM_60                 33003
#define ID_VIEW_ZOOM_50                 33004
#define ID_VIEW_ZOOM_40                 33005
#define ID_VIEW_ZOOM_20                 33007
#define ID_VIEW_ZOOM_10                 33008
#define ID_VIEW_ZOOM_30                 33009
#define ID_TOOLS_GENERATE_CODE          33010
#define ID_LINE_ARROW                   33011
#define ID_LINE_STYLE_SOLID             33012
#define ID_LINE_STYLE_DASH              33013
#define ID_LINE_STYLE_DOT               33014
#define ID_LINE_THICKNESS_1             33015
#define ID_LINE_THICKNESS_2             33016
#define ID_LINE_THICKNESS_3             33017
#define ID_LINE_THICKNESS_4             33018
#define ID_TB_BOX                       33025
#define ID_TB_CIRCLE                    33026
#define ID_BUTTON33030                  33030
#define ID_TB_ROUNDBOXA                 33030
#define ID_FILE_MRU_WS1                 0xE110
#define ID_FILE_MRU_WS2                 0xE111
#define ID_FILE_MRU_WS3                 0xE112
#define ID_FILE_MRU_WS4                 0xE113
#define ID_FILE_MRU_WS5                 0xE114
#define ID_FILE_MRU_WS6                 0xE115
#define ID_FILE_MRU_WS7                 0xE116
#define ID_FILE_MRU_WS8                 0xE117
#define ID_FILE_MRU_WS9                 0xE118
#define ID_FILE_MRU_WS10                0xE119
#define ID_FILE_MRU_WS11                0xE11A
#define ID_FILE_MRU_WS12                0xE11B
#define ID_FILE_MRU_WS13                0xE11C
#define ID_FILE_MRU_WS14                0xE11D
#define ID_FILE_MRU_WS15                0xE11E
#define ID_FILE_MRU_WS16                0xE11F
#define ID_NULL                         61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        277
#define _APS_NEXT_COMMAND_VALUE         33031
#define _APS_NEXT_CONTROL_VALUE         1175
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
