#ifndef _TIPSTRING_H
#define _TIPSTRING_H

char *tip_str[] = {
"",
"Welcome to the OODesigner: CASE Tool for UML",
" ",
"We've got a small set of tips yet. More tips will be supplied in the",
"next version. If you turn Tip of the Day off, it is available from the Help menu.", 
"",
"Data member specification example:",
"+size:Area = (100,100)",
"#visibility:Boolean = invisible",
"+deaultSize:Rectangle {static}",
"#maximumSize:Rectangle {static}",
"-xptr:XWindowPtr {transient}",
"",
"Data member specification syntax:",
"[+#-] <name> : <type-expression> = <initial-value> { <property-string> }",
"where <property-string> is one of:",
"static,transient,final,afx_data,afx_field",
"",
"Some node objects like actor, wide package could be copied and pasted across"
"the diagrams. But others and link objects could not."
"",
"There are three kinds of Properties Dialog:",
"(1) Class Properties Dialog: edit resources for class properties",
"(2) Data Member Properties Dialog: edit resources for data members",
"(3) Member Function Properties Dialog: edit resources for member functions",
"Depending on the position you popup a menu in class diagram,",
"one of the dialogs will be activated.",
"",
"Member function specification syntax:",
"[+#-] <name> (<argment-list>) : <return-type-expression> { <property-string> }",
"where <property-string> is one of:",
"virtual,inline,const,abstract,native,synchronized,static,final,afx_msg,afx_virtual",
"",
"You can use a Data Member Properties dialog to specify multi-line initial value.",
"",
"The following connections are forkable:",
"in class diagram: generalization, aggregation, dependency, association",
"in activity diagram: trigger",
"the other connections like transition, use case link are not forkable.",
"",
"If you delete any file within the tree browser, the backup file will be",
"automatically saved in the backup directory.",
"",
"When editing, you can press arrow buttons to move cursor.",
"",
"Data member specification example:",
"-m_pWin:CWnd* = NULL",
"colors[3]:Color",
"points[0,MAX]:Point",
"array:Vector[10][10]",
"",
"When you capture a view or the screen using the camera in toobar,",
"the captured image is also being stored in the clipboard.",
"",
"Member function specification example:",
"+display():Location",
"+hide() {const}",
"+Create() {static}",
"-attachXWindow(xwin:XWindow*)",
"+operator[](i:int):int",
"+Revoke(dwRegister:[in] DWORD) : HRESULT = 0 {virtual}",
"", 
"You can use Properties Dialog to edit member resources or",
"you can edit equivalent resources in editing mode",
"",
"Procedure to make a branch from a line segment:",
"(1) Click/select a line segment you want",
"(2) Wait a minute - don't move the mouse",
"(3) a \"X\" sign will be displayed on the line segment",
"(4) You can fork a new branch from that position",
"",
"When editing, you can press Ctrl+[Backspace] to delete a line.",
"",
"This is the last tip.",
"",
""
};

#define NOFTIPS ((sizeof tip_str / sizeof tip_str[0]) - 2)

#endif